# Generated by Django 5.0.1 on 2024-04-15 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=300)),
                ('profile_image_url', models.CharField(max_length=200)),
                ('facebook', models.URLField(max_length=100)),
                ('instagram', models.URLField(max_length=100)),
                ('twitter', models.URLField(max_length=100)),
                ('threads', models.URLField(max_length=100)),
                ('telegram', models.URLField(max_length=100)),
                ('whatsapp', models.URLField(max_length=100)),
                ('youtube', models.URLField(max_length=100)),
                ('discord', models.URLField(max_length=100)),
                ('github', models.URLField(max_length=100)),
                ('linkedin', models.URLField(max_length=100)),
                ('snapchat', models.URLField(max_length=100)),
                ('email', models.URLField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=15)),
                ('url', models.URLField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('product_image_url', models.URLField()),
                ('price', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
