# Generated by Django 5.0.1 on 2024-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extralinks',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discord',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='snapchat',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='threads',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
