# Generated by Django 5.0.1 on 2024-04-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_extralinks_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='product_image_url',
            field=models.CharField(max_length=200),
        ),
    ]
